#!/usr/bin/env python3
"""Consolidate every extracted map into one cross-map design catalog.

Reads data/maps/*.json (produced by extract_map.py) and writes:
  data/catalog/units.json      one row per unit type per map, normalised
  data/catalog/summary.json    per-map counts, economy constants, regions
  docs/generated/units.md      readable tables
"""
import os, re, sys, json, glob, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COLOR = re.compile(r'\|c[0-9a-fA-F]{8}|\|r|\|n')


def clean(s):
    """Strip Warcraft colour/linebreak escape codes from display text."""
    if not isinstance(s, str):
        return s
    return COLOR.sub(' ', s).strip()


def first(v):
    return v[0] if isinstance(v, list) else v


# A building that trains something, or a unit that walks. Decided by the fields
# the map author actually filled in, since base ids are reused freely.
def classify(u):
    if u.get('trains') or u.get('builds'):
        return 'producer'
    if u.get('is_building') == 1 or (u.get('atk1_range') or 0) and not u.get('move_speed'):
        return 'structure'
    if u.get('food_used') == 10 and u.get('cost_gold') == 85:
        return 'hero'
    if u.get('move_speed'):
        return 'unit'
    return 'other'


FIELDS = ['name', 'tip', 'ubertip', 'hp_max', 'mana_max', 'cost_gold', 'cost_lumber',
          'food_used', 'food_made', 'build_time', 'atk1_dmg_base', 'atk1_dice',
          'atk1_sides', 'atk1_cooldown', 'atk1_range', 'atk1_targets', 'atk1_type',
          'atk2_dmg_base', 'atk2_range', 'armor', 'defense_type', 'move_speed',
          'move_type', 'sight_day', 'level', 'abilities_normal', 'abilities_hero',
          'trains', 'builds', 'upgrades_to', 'requirements', 'model', 'icon']


def main():
    os.makedirs(os.path.join(ROOT, 'data/catalog'), exist_ok=True)
    os.makedirs(os.path.join(ROOT, 'docs/generated'), exist_ok=True)

    rows, summary = [], {}
    for p in sorted(glob.glob(os.path.join(ROOT, 'data/maps/*.json'))):
        d = json.load(open(p))
        m = d['map']
        units = d.get('units', {})
        entries = (units.get('custom', []) + units.get('modified_standard', [])) \
            if isinstance(units, dict) else []
        for e in entries:
            r = {'map': m, 'id': e['id'] or e['base'], 'base': e['base']}
            for f in FIELDS:
                if f in e:
                    r[f] = clean(first(e[f]))
            r['role'] = classify(e)
            rows.append(r)

        info = d.get('info', {})
        summary[m] = {
            'name': clean(info.get('name')),
            'author': clean(info.get('author')),
            'description': clean(info.get('description')),
            'playable_size': [info.get('playable_w'), info.get('playable_h')],
            'tileset': info.get('tileset'),
            'players': len(info.get('players') or []),
            'forces': [{'name': clean(f['name']), 'mask': '0x%08x' % f['player_mask']}
                       for f in info.get('forces') or []],
            'counts': {k: (len(v.get('custom', [])) + len(v.get('modified_standard', [])))
                       for k, v in d.items()
                       if isinstance(v, dict) and 'custom' in v},
            'regions': [{'name': r['name'],
                         'rect': [r['left'], r['bottom'], r['right'], r['top']]}
                        for r in d.get('regions', []) if isinstance(r, dict)],
            'preplaced': len(d.get('preplaced_units', []))
                         if isinstance(d.get('preplaced_units'), list) else None,
            'files': len(d['archive']['files']),
        }

    json.dump(rows, open(os.path.join(ROOT, 'data/catalog/units.json'), 'w'),
              indent=1, ensure_ascii=False)
    json.dump(summary, open(os.path.join(ROOT, 'data/catalog/summary.json'), 'w'),
              indent=1, ensure_ascii=False)

    # readable tables
    out = ['# Unit catalog (generated)',
           '',
           'Generated by `tools/build_catalog.py` from `data/maps/*.json`. Do not edit by hand.',
           '']
    by_map = collections.defaultdict(list)
    for r in rows:
        by_map[r['map']].append(r)
    for m in sorted(by_map):
        out += ['## %s' % m, '',
                '| id | base | name | role | gold | food | HP | dmg | armor | speed | build |',
                '|---|---|---|---|---|---|---|---|---|---|---|']
        for r in sorted(by_map[m], key=lambda x: (x['role'], str(x.get('name') or ''))):
            out.append('| `%s` | `%s` | %s | %s | %s | %s | %s | %s | %s | %s | %s |' % (
                r['id'], r['base'], (r.get('name') or '').replace('|', '\\|'), r['role'],
                r.get('cost_gold', ''), r.get('food_used', ''), r.get('hp_max', ''),
                r.get('atk1_dmg_base', ''), r.get('armor', ''),
                r.get('move_speed', ''), r.get('build_time', '')))
        out.append('')
    open(os.path.join(ROOT, 'docs/generated/units.md'), 'w').write('\n'.join(out))

    print('%d unit rows across %d maps' % (len(rows), len(summary)))
    for m, s in summary.items():
        print('  %-36s %s' % (m, s['counts']))


if __name__ == '__main__':
    main()
