#!/usr/bin/env python3
"""Join the spawner table with unit stats to show what each building actually buys.

For every "build X -> it trains Y every N seconds" pair, work out the sustained
value the building produces: HP and damage per second of army, per gold spent.
That is the number that decides whether a building is worth its price, and it is
what has to survive the port to mobile.

Usage: python3 tools/spawner_economics.py
"""
import os, sys, json, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def unit_index(mapname):
    p = os.path.join(ROOT, 'data/maps', mapname + '.json')
    d = json.load(open(p))
    u = d.get('units', {})
    idx = {}
    for e in (u.get('custom', []) + u.get('modified_standard', [])):
        idx[e['id'] or e['base']] = e
    return idx


def num(e, key, default=0):
    v = e.get(key, default)
    if isinstance(v, list):
        v = v[0]
    return v if isinstance(v, (int, float)) else default


def name(e):
    v = e.get('name', '')
    return (v[0] if isinstance(v, list) else v) or ''


def hit(e):
    """Mean damage of one attack-1 swing: base + dice * (sides + 1) / 2."""
    base = num(e, 'atk1_dmg_base')
    dice, sides = num(e, 'atk1_dice'), num(e, 'atk1_sides')
    return round(base + (dice * (sides + 1) / 2.0 if dice and sides else 0), 1)


def dps(e):
    """Damage per second, when the map overrode the attack cooldown.

    Most units keep the cooldown of the stock Warcraft unit they derive from,
    and that table does not ship inside the map — so this is None more often
    than not. Use `dmg_per_hit` when it is.
    """
    cd = num(e, 'atk1_cooldown') or 0
    return round(hit(e) / cd, 1) if cd else None


def main():
    rows = []
    for p in sorted(glob.glob(os.path.join(ROOT, 'data/rules/*.json'))):
        m = os.path.basename(p)[:-5]
        rules = json.load(open(p))
        idx = unit_index(m)
        period = rules.get('autotrain_period_seconds') or 0
        for s in rules['spawners']:
            b, t = idx.get(s['building']), idx.get(s['trains'])
            if not b or not t:
                # a standard Warcraft unit the map never modified
                b, t = b or {}, t or {}
            gold = num(b, 'cost_gold')
            row = {
                'map': m, 'building_id': s['building'], 'building': name(b),
                'gold': gold, 'food': num(b, 'food_used'),
                'build_time': num(b, 'build_time'),
                'unit_id': s['trains'], 'unit': name(t),
                'unit_hp': num(t, 'hp_max'), 'unit_dmg_per_hit': hit(t), 'unit_dps': dps(t),
                'unit_armor': num(t, 'armor'), 'unit_speed': num(t, 'move_speed'),
                'spawn_period_s': period,
            }
            if period and gold:
                row['hp_per_sec'] = round(row['unit_hp'] / period, 1)
                row['hp_per_sec_per_100g'] = round(row['unit_hp'] / period / gold * 100, 1)
                if row['unit_dps']:
                    row['dps_added_per_sec'] = round(row['unit_dps'] / period, 2)
                    row['dps_per_sec_per_100g'] = round(
                        row['unit_dps'] / period / gold * 100, 2)
            rows.append(row)

    os.makedirs(os.path.join(ROOT, 'data/catalog'), exist_ok=True)
    json.dump(rows, open(os.path.join(ROOT, 'data/catalog/spawner_economics.json'), 'w'),
              indent=1, ensure_ascii=False)

    out = ['# Spawner economics (generated)', '',
           'Generated by `tools/spawner_economics.py`. Do not edit by hand.', '',
           'A spawner is bought once and then produces one unit every '
           '`spawn_period` seconds, forever. So its real price is not the unit — '
           'it is *army value per second per gold invested*. The last two columns '
           'are the balance levers.', '']
    cur = None
    for r in rows:
        if r['map'] != cur:
            cur = r['map']
            out += ['## %s  (tick %ss)' % (cur, r['spawn_period_s']), '',
                    '| building | gold | food | trains | HP | dmg/hit | DPS | HP/s per 100g |',
                    '|---|---|---|---|---|---|---|---|']
        out.append('| %s `%s` | %s | %s | %s `%s` | %s | %s | %s | %s |' % (
            r['building'] or '—', r['building_id'], r['gold'] or '—', r['food'] or '—',
            r['unit'] or '—', r['unit_id'], r['unit_hp'] or '—',
            r['unit_dmg_per_hit'] or '—',
            r['unit_dps'] if r['unit_dps'] is not None else 'inherited',
            r.get('hp_per_sec_per_100g', '—')))
    out += ['',
            'A `DPS` of `inherited` means the map never overrode that unit\'s attack '
            'cooldown, so it still uses the stock Warcraft value — which lives in the '
            'game client, not in the map. Only `dmg/hit` is knowable from these files.',
            '']
    open(os.path.join(ROOT, 'docs/generated/spawners.md'), 'w').write('\n'.join(out))
    print('%d spawner rows -> docs/generated/spawners.md' % len(rows))


if __name__ == '__main__':
    main()
